name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "**"

jobs:
  release-bundle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache pnpm modules
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.pnpm-store
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml', 'rollup.config.js') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: latest
          run_install: false

      - name: Install Packages
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Create Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
          artifacts: ./dist/power-flow-card.js
